DROP TABLE OrderTable;

CREATE TABLE OrderTable (Client_ID VARCHAR(200), Order_ID VARCHAR(200), PRIMARY KEY (Order_ID));

INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_5','Order_0'),('Client_1','Order_1'),('Client_2','Order_2'),('Client_4','Order_3'),('Client_3','Order_4'),('Client_8','Order_5'),('Client_7','Order_6'),('Client_2','Order_7'),('Client_7','Order_8'),('Client_8','Order_9');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_6','Order_10'),('Client_9','Order_11'),('Client_6','Order_12'),('Client_4','Order_13'),('Client_5','Order_14'),('Client_2','Order_15'),('Client_9','Order_16'),('Client_2','Order_17'),('Client_0','Order_18'),('Client_6','Order_19');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_6','Order_20'),('Client_7','Order_21'),('Client_4','Order_22'),('Client_4','Order_23'),('Client_7','Order_24'),('Client_6','Order_25'),('Client_3','Order_26'),('Client_8','Order_27'),('Client_9','Order_28'),('Client_7','Order_29');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_0','Order_30'),('Client_2','Order_31'),('Client_1','Order_32'),('Client_7','Order_33'),('Client_4','Order_34'),('Client_5','Order_35'),('Client_0','Order_36'),('Client_4','Order_37'),('Client_6','Order_38'),('Client_1','Order_39');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_9','Order_40'),('Client_0','Order_41'),('Client_4','Order_42'),('Client_8','Order_43'),('Client_8','Order_44'),('Client_3','Order_45'),('Client_3','Order_46'),('Client_2','Order_47'),('Client_4','Order_48'),('Client_6','Order_49');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_6','Order_50'),('Client_5','Order_51'),('Client_5','Order_52'),('Client_3','Order_53'),('Client_6','Order_54'),('Client_6','Order_55'),('Client_4','Order_56'),('Client_6','Order_57'),('Client_1','Order_58'),('Client_2','Order_59');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_3','Order_60'),('Client_6','Order_61'),('Client_8','Order_62'),('Client_3','Order_63'),('Client_0','Order_64'),('Client_0','Order_65'),('Client_2','Order_66'),('Client_0','Order_67'),('Client_3','Order_68'),('Client_1','Order_69');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_8','Order_70'),('Client_3','Order_71'),('Client_8','Order_72'),('Client_5','Order_73'),('Client_3','Order_74'),('Client_9','Order_75'),('Client_8','Order_76'),('Client_4','Order_77'),('Client_0','Order_78'),('Client_8','Order_79');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_1','Order_80'),('Client_1','Order_81'),('Client_3','Order_82'),('Client_0','Order_83'),('Client_2','Order_84'),('Client_2','Order_85'),('Client_1','Order_86'),('Client_7','Order_87'),('Client_1','Order_88'),('Client_5','Order_89');
INSERT INTO OrderTable (Client_ID, Order_ID) VALUES ('Client_2','Order_90'),('Client_8','Order_91'),('Client_8','Order_92'),('Client_3','Order_93'),('Client_9','Order_94'),('Client_7','Order_95'),('Client_1','Order_96'),('Client_0','Order_97'),('Client_4','Order_98'),('Client_4','Order_99');
