DROP TABLE ClientTable;

CREATE TABLE ClientTable (Email VARCHAR(200), Address VARCHAR(200), Client_ID VARCHAR(200), PRIMARY KEY (Client_ID));

INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_0@blah.com','Client_0 Address','Client_0'),('Client_1@blah.com','Client_1 Address','Client_1'),('Client_2@blah.com','Client_2 Address','Client_2'),('Client_3@blah.com','Client_3 Address','Client_3'),('Client_4@blah.com','Client_4 Address','Client_4'),('Client_5@blah.com','Client_5 Address','Client_5'),('Client_6@blah.com','Client_6 Address','Client_6'),('Client_7@blah.com','Client_7 Address','Client_7'),('Client_8@blah.com','Client_8 Address','Client_8'),('Client_9@blah.com','Client_9 Address','Client_9');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_10@blah.com','Client_10 Address','Client_10'),('Client_11@blah.com','Client_11 Address','Client_11'),('Client_12@blah.com','Client_12 Address','Client_12'),('Client_13@blah.com','Client_13 Address','Client_13'),('Client_14@blah.com','Client_14 Address','Client_14'),('Client_15@blah.com','Client_15 Address','Client_15'),('Client_16@blah.com','Client_16 Address','Client_16'),('Client_17@blah.com','Client_17 Address','Client_17'),('Client_18@blah.com','Client_18 Address','Client_18'),('Client_19@blah.com','Client_19 Address','Client_19');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_20@blah.com','Client_20 Address','Client_20'),('Client_21@blah.com','Client_21 Address','Client_21'),('Client_22@blah.com','Client_22 Address','Client_22'),('Client_23@blah.com','Client_23 Address','Client_23'),('Client_24@blah.com','Client_24 Address','Client_24'),('Client_25@blah.com','Client_25 Address','Client_25'),('Client_26@blah.com','Client_26 Address','Client_26'),('Client_27@blah.com','Client_27 Address','Client_27'),('Client_28@blah.com','Client_28 Address','Client_28'),('Client_29@blah.com','Client_29 Address','Client_29');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_30@blah.com','Client_30 Address','Client_30'),('Client_31@blah.com','Client_31 Address','Client_31'),('Client_32@blah.com','Client_32 Address','Client_32'),('Client_33@blah.com','Client_33 Address','Client_33'),('Client_34@blah.com','Client_34 Address','Client_34'),('Client_35@blah.com','Client_35 Address','Client_35'),('Client_36@blah.com','Client_36 Address','Client_36'),('Client_37@blah.com','Client_37 Address','Client_37'),('Client_38@blah.com','Client_38 Address','Client_38'),('Client_39@blah.com','Client_39 Address','Client_39');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_40@blah.com','Client_40 Address','Client_40'),('Client_41@blah.com','Client_41 Address','Client_41'),('Client_42@blah.com','Client_42 Address','Client_42'),('Client_43@blah.com','Client_43 Address','Client_43'),('Client_44@blah.com','Client_44 Address','Client_44'),('Client_45@blah.com','Client_45 Address','Client_45'),('Client_46@blah.com','Client_46 Address','Client_46'),('Client_47@blah.com','Client_47 Address','Client_47'),('Client_48@blah.com','Client_48 Address','Client_48'),('Client_49@blah.com','Client_49 Address','Client_49');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_50@blah.com','Client_50 Address','Client_50'),('Client_51@blah.com','Client_51 Address','Client_51'),('Client_52@blah.com','Client_52 Address','Client_52'),('Client_53@blah.com','Client_53 Address','Client_53'),('Client_54@blah.com','Client_54 Address','Client_54'),('Client_55@blah.com','Client_55 Address','Client_55'),('Client_56@blah.com','Client_56 Address','Client_56'),('Client_57@blah.com','Client_57 Address','Client_57'),('Client_58@blah.com','Client_58 Address','Client_58'),('Client_59@blah.com','Client_59 Address','Client_59');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_60@blah.com','Client_60 Address','Client_60'),('Client_61@blah.com','Client_61 Address','Client_61'),('Client_62@blah.com','Client_62 Address','Client_62'),('Client_63@blah.com','Client_63 Address','Client_63'),('Client_64@blah.com','Client_64 Address','Client_64'),('Client_65@blah.com','Client_65 Address','Client_65'),('Client_66@blah.com','Client_66 Address','Client_66'),('Client_67@blah.com','Client_67 Address','Client_67'),('Client_68@blah.com','Client_68 Address','Client_68'),('Client_69@blah.com','Client_69 Address','Client_69');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_70@blah.com','Client_70 Address','Client_70'),('Client_71@blah.com','Client_71 Address','Client_71'),('Client_72@blah.com','Client_72 Address','Client_72'),('Client_73@blah.com','Client_73 Address','Client_73'),('Client_74@blah.com','Client_74 Address','Client_74'),('Client_75@blah.com','Client_75 Address','Client_75'),('Client_76@blah.com','Client_76 Address','Client_76'),('Client_77@blah.com','Client_77 Address','Client_77'),('Client_78@blah.com','Client_78 Address','Client_78'),('Client_79@blah.com','Client_79 Address','Client_79');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_80@blah.com','Client_80 Address','Client_80'),('Client_81@blah.com','Client_81 Address','Client_81'),('Client_82@blah.com','Client_82 Address','Client_82'),('Client_83@blah.com','Client_83 Address','Client_83'),('Client_84@blah.com','Client_84 Address','Client_84'),('Client_85@blah.com','Client_85 Address','Client_85'),('Client_86@blah.com','Client_86 Address','Client_86'),('Client_87@blah.com','Client_87 Address','Client_87'),('Client_88@blah.com','Client_88 Address','Client_88'),('Client_89@blah.com','Client_89 Address','Client_89');
INSERT INTO ClientTable (Email, Address, Client_ID) VALUES ('Client_90@blah.com','Client_90 Address','Client_90'),('Client_91@blah.com','Client_91 Address','Client_91'),('Client_92@blah.com','Client_92 Address','Client_92'),('Client_93@blah.com','Client_93 Address','Client_93'),('Client_94@blah.com','Client_94 Address','Client_94'),('Client_95@blah.com','Client_95 Address','Client_95'),('Client_96@blah.com','Client_96 Address','Client_96'),('Client_97@blah.com','Client_97 Address','Client_97'),('Client_98@blah.com','Client_98 Address','Client_98'),('Client_99@blah.com','Client_99 Address','Client_99');
