DROP TABLE ProductTable;

CREATE TABLE ProductTable (Description VARCHAR(200), Product_ID VARCHAR(200), PRIMARY KEY (Product_ID));

INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_0'),('blahh','Product_1'),('blahh','Product_2'),('blahh','Product_3'),('blahh','Product_4'),('blahh','Product_5'),('blahh','Product_6'),('blahh','Product_7'),('blahh','Product_8'),('blahh','Product_9');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_10'),('blahh','Product_11'),('blahh','Product_12'),('blahh','Product_13'),('blahh','Product_14'),('blahh','Product_15'),('blahh','Product_16'),('blahh','Product_17'),('blahh','Product_18'),('blahh','Product_19');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_20'),('blahh','Product_21'),('blahh','Product_22'),('blahh','Product_23'),('blahh','Product_24'),('blahh','Product_25'),('blahh','Product_26'),('blahh','Product_27'),('blahh','Product_28'),('blahh','Product_29');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_30'),('blahh','Product_31'),('blahh','Product_32'),('blahh','Product_33'),('blahh','Product_34'),('blahh','Product_35'),('blahh','Product_36'),('blahh','Product_37'),('blahh','Product_38'),('blahh','Product_39');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_40'),('blahh','Product_41'),('blahh','Product_42'),('blahh','Product_43'),('blahh','Product_44'),('blahh','Product_45'),('blahh','Product_46'),('blahh','Product_47'),('blahh','Product_48'),('blahh','Product_49');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_50'),('blahh','Product_51'),('blahh','Product_52'),('blahh','Product_53'),('blahh','Product_54'),('blahh','Product_55'),('blahh','Product_56'),('blahh','Product_57'),('blahh','Product_58'),('blahh','Product_59');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_60'),('blahh','Product_61'),('blahh','Product_62'),('blahh','Product_63'),('blahh','Product_64'),('blahh','Product_65'),('blahh','Product_66'),('blahh','Product_67'),('blahh','Product_68'),('blahh','Product_69');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_70'),('blahh','Product_71'),('blahh','Product_72'),('blahh','Product_73'),('blahh','Product_74'),('blahh','Product_75'),('blahh','Product_76'),('blahh','Product_77'),('blahh','Product_78'),('blahh','Product_79');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_80'),('blahh','Product_81'),('blahh','Product_82'),('blahh','Product_83'),('blahh','Product_84'),('blahh','Product_85'),('blahh','Product_86'),('blahh','Product_87'),('blahh','Product_88'),('blahh','Product_89');
INSERT INTO ProductTable (Description, Product_ID) VALUES ('blahh','Product_90'),('blahh','Product_91'),('blahh','Product_92'),('blahh','Product_93'),('blahh','Product_94'),('blahh','Product_95'),('blahh','Product_96'),('blahh','Product_97'),('blahh','Product_98'),('blahh','Product_99');
